version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build-image:
    machine: true
    environment:
      TOKEN: foobar
      AWS_ECR_REGISTRY_ID: 123456789012
      AWS_REGION: us-east-1
    steps:
      - checkout
      - aws-ecr/build-image:
          extra-build-args: '--build-arg token=$TOKEN'
          push-image: false
          repo: kelvintaywl/test

workflows:
  explore:
    jobs:
      - build-image
