version: 2.1

orbs:
  # same version used by circleci/aws-ecr@8.1.3
  # see https://github.com/CircleCI-Public/aws-ecr-orb/blob/v8.1.3/src/%40orb.yml#L11
  aws-cli: circleci/aws-cli@3.1.3
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  install-cli:
    executor: aws-ecr/default
    environment:
      PREFIX: foobar
    steps:
      - checkout
      - aws-cli/setup

workflows:
  main:
    jobs:
      - install-cli
